# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
#    security_tokens: [main]
    email:
        enabled: true
        sender_email: 'noreply@tasklinker.com'
        sender_name: 'Tasklinker'
        digits: 6
        template: 'security/2fa_email.html.twig'
